# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files
COPY package*.json tsconfig.json ./

# Copy source code
COPY . .

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and runtime essentials
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/cli.js ./cli.js
COPY --from=builder /app/index.js ./index.js
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

# Runtime environment variables
ENV BROWSERBASE_API_KEY=""
ENV BROWSERBASE_PROJECT_ID=""

ENTRYPOINT ["node", "./cli.js"]
